name: CI/CD — TITANIC API

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login \
            --username AWS \
            --password-stdin 718100329950.dkr.ecr.eu-west-3.amazonaws.com

      - name: Build and push to ECR
        run: |
          docker build -t titanic-mlops .
          docker tag titanic-mlops:latest \
            718100329950.dkr.ecr.eu-west-3.amazonaws.com/titanic-mlops:latest
          docker push \
            718100329950.dkr.ecr.eu-west-3.amazonaws.com/titanic-mlops:latest

      - name: Deploy sur EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-west-3 | docker login \
              --username AWS \
              --password-stdin 718100329950.dkr.ecr.eu-west-3.amazonaws.com
            docker stop titanic || true
            docker rm titanic || true
            docker pull 718100329950.dkr.ecr.eu-west-3.amazonaws.com/titanic-mlops:latest
            docker run -d -p 8002:8000 --name titanic \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              718100329950.dkr.ecr.eu-west-3.amazonaws.com/titanic-mlops:latest
